### PR TITLE
Refactor the year filters

### PR DESCRIPTION
**Pull request by mrchrisadams**
This PR:

- make the classes DRYer, using a mixin instead of inheritance
- uses a range filter query instead of two filters (thanks @jonathan-s  👍 )
- adds tests!

### CODE REVIEW

**Comment by jonathan-s** [comment]
Performance improved then?

**Comment by mrchrisadams** [comment]
I haven't spent any time trying to speed up the queries yet, but I'm not sure if the filtering is even used yet.

If it is, and it's used often enough to justify the time, then I guess we will but it's less of a priority right now than the other work.

**Comment by mrchrisadams** [comment]
Wow, I've been trying it out, and queries using range turn out to be _much_ faster - as in 20-30x faster now.

Thanks amigo, that's so much better 👍

**Comment by jonathan-s** [comment]
Golden 👌

**Pull request merged**
