### PR TITLE
Update content of verification approval email

### PR DESCRIPTION
**Pull request by fershad**
The main purpose of this PR is to update the content of the verification approval email for new providers. The aim is to provide more useful links and structured guidance on how providers can manage their approved listings.

Another change included in this PR is to dynamically adjust the email subject for verification request & approval emails to indicate if they are "new requests" or "updates".

### CODE REVIEW

**Comment by fershad** [comment]
Okay that's wild. The commits listed above are waaaay more than the ones I created in this branch/PR. Looks like it's pulled in a bunch of old work as well for some reason.

@mrchrisadams let me know if you want me to close this PR and create a new one.

**Comment by mrchrisadams** [comment]
hey @fershad can you please link to the corresponding trello card for this one?

I think some of this code might already be merged into master, but it might not have been pushed to staging, based on the c compare view below:

https://github.com/thegreenwebfoundation/admin-portal/compare/master...fi-update-verification-emails

I'm also reachable in Zulip

**Comment by mrchrisadams** [comment]
Thanks fish. For our future selves:

- we agreed it's cool to force push these changes to staging, to preview them, as we make no guarantees that staging is a coherent history
- the final PR would be against the master branch, as a number of the commits have already been merged in with PR #539

**Comment by mrchrisadams** [comment]
See also PR #544  where just the copy changes are listed.

**Pull request merged**
