### PR TITLE
Added yml config for Green Metrics Tool

### PR DESCRIPTION
**Pull request by jcamilleri-scottlogic**
associated test.

### CODE REVIEW

**Comment by mrchrisadams** [comment]
Thanks for this @jcamilleri-scottlogic  - as discussed, I'll add the necessary changes to run the django container in the setup

**Comment by mrchrisadams** [comment]
ok, once #588 is merged in I think we'll be in shape to update the usage scenarios for testing  in GMT:

Some feedback from Arne at Green Coding Solutions:

> I have given the PR a quick look and the usage_scenario file. A few things I saw:
> 
> - flow is not correctly indented. Must be at root level
> - depends_on is no dict. must be list
> - There is no Dockerfile to build the 'mariadb' service
> ...
> 
> Since it is in Draft I assume that is expected. I just wanted to quickly try and this is what I encountered.

@jcamilleri-scottlogic  - I'll make the commits to this branch as I work to get the usage scenarios generating useable numbers.

**Comment by mrchrisadams** [comment]
@jcamilleri-scottlogic  - I don't think I can make commits to this branch, so I've made a new PR, pulling in your commit, so that you folks are recognised for working on the PR:

https://github.com/thegreenwebfoundation/admin-portal/pull/589


I've also added you as a collaborator for the time being, so you are able to make pushes to that PR/branch if need be.

**Comment by jcamilleri-scottlogic** [comment]
Thanks Chris. I saw Arne's comments about the YML file - I'll see if I can get those parts fixed up this afternoon.

**Comment by mrchrisadams** [comment]
@jcamilleri-scottlogic  - I'm making notes as I work in #589 - it might be worth comparing notes there

**Comment by mrchrisadams** [comment]
I'm closing this in favour of the other PR #589 where @jcamilleri-scottlogic continued to work on this.

**Pull request closed without merging**
